server: # REST and WS server
  port: 2635
  address:  0.0.0.0
spring:
  main:
    banner-mode: log
lavalink:
  server:
    password: "Mypassword"
    sources:
      youtube: true
      bandcamp: false
      soundcloud: true
      twitch: false
      vimeo: false
      mixer: false
      http: true
      local: false # Set to true to play local files
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6 # Number of pages at 100 each
    gc-warnings: true

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  #  tags:
  #    some_key: some_value
  #    another_key: another_value

logging:
  file:
    max-history: 30
    max-size: 1GB
  path: ./logs/